[package]
name = "llama2rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
bincode = "1.3.3"
byteorder = "1.3.3"
rayon="1.7.0"


[profile.release]
lto = true
codegen-units = 1